# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 03:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publisher',
            old_name='webstie',
            new_name='website',
        ),
    ]
