# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 06:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20170624_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='num_pages',
        ),
    ]
