# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='pub_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
